# Generated by Django 3.0.3 on 2020-08-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(3, 'high'), (2, 'medium'), (1, 'small')], default=2),
        ),
    ]
