# Generated by Django 3.0.3 on 2020-08-20 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(3, 'high'), (2, 'medium'), (1, 'small')], default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='planed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
